### ISSUE TITLE
Дистанция =0 это ошибка, а скорость =0(т.е. деление на 0) допускается

### ISSUE THREAD

**Issue by tgurskaya96** [maxtsiushkevich/labJavaBSUIR#3]
https://github.com/maxtsiushkevich/labJavaBSUIR/blob/f500387eb8d13ccac6c5bad67192d215e849d8ea/src/main/java/com/example/labjava/GetTime.java#L23

**Comment by maxtsiushkevich** [comment]
При скорости <0 выбрасывается 400 ошибка, при делении на 0 выбрасывается 500
